train_src: ../datasets/deu-eng/toks/train.eng.tok
train_tgt: ../datasets/deu-eng/toks/train.deu.tok
valid_src: ../datasets/deu-eng/toks/dev.eng.tok
valid_tgt: ../datasets/deu-eng/toks/dev.deu.tok
truncate: True
src_len: 512
tgt_len: 512
shared: False
# max_types: 4000
max_src_types: 770
max_tgt_types: 8000
# pieces: ngram
src_pieces: factorizer
tgt_pieces: bpe
src_factorizer: ../factorizer-models/english.dawg
# tgt_factorizer: .
